### ISSUE TITLE
【图标】抓取的时候建议把谷歌引擎换掉

### ISSUE THREAD

**Issue by 990721830** [qxinGitHub/searchEngineJump#11]
今天正好节点被墙的时候发现的.....
如果没有开代理的话显示不了ico.......
建议换成国内的

1丶http://statics.dnspod.cn/proxy_favicon/_/favicon?domain=域名

2丶域名 /favicon.ico

**Comment by qxinGitHub** [comment]
好，建议已收到，届时增加个设置选项，让用户自由选择，不过需要过几天。
目前脚本里的策略是在添加搜索的时候，检测能否链接至谷歌，若是能，就用谷歌的获取，不能，则在域名后加上favicon.ico。

还有就是你提的另一个问题可能需要好久才能解决。首先，是可以实现拖动文字到上面去搜索。但是，在拖动文字的情况下，鼠标划过时无法展开搜索列表，所以，受限于能力，在没找到合适的方法之前，拖拽搜索可能不会去实现。。。

**Comment by qxinGitHub** [comment]
对于已经存在的，还是不行，只能改变将来添加新搜索项目时，抓取图标的方式。或许在将来加个刷新按钮。
![tim 20180803230534](https://user-images.githubusercontent.com/19566881/43650383-30b363e2-9772-11e8-8365-360da318966f.png)
0为自动，能连接谷歌的情况下用谷歌获取，无法连接的情况下，域名加favicon.ico获取；
1为域名加favicon获取，
2为使用谷歌获取，
3为使用dnspot的服务获取(不过经常失败)。
或者添加网址，关键字使用%s代替，未测试

**Comment by 990721830** [comment]
好的......
