### ISSUE TITLE
在网页的输入框和任意地方选中文字，顶部就会弹出，很遮挡视线，且没有关闭此功能的按钮

### ISSUE THREAD

**Issue by CangWeiohh** [qxinGitHub/searchEngineJump#126]

**Comment by mingzigequ** [comment]
赞同

**Comment by CangWeiohh** [comment]
已经解决了




仓唯
***@***.***







                       
原始邮件
                       
                     

发件人："mingzigequ"< ***@***.*** &gt;;

发件时间：2022/12/31 22:26

收件人："qxinGitHub/searchEngineJump"< ***@***.*** &gt;;

抄送人："CangWei"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [qxinGitHub/searchEngineJump] 在网页的输入框和任意地方选中文字，顶部就会弹出，很遮挡视线，且没有关闭此功能的按钮 (Issue #126)




 
赞同
 
&mdash;

**Comment by piaoyun** [comment]
怎么解决的呢。

**Comment by CurssedCoffin** [comment]
怎么解决的呢。

**Comment by CurssedCoffin** [comment]
设置 function selectSearch(e) 中的 selectSearchMode = false; 即可

**Comment by JerryYang-30** [comment]
> 已经解决了 仓唯 ***@***.*** 原始邮件 发件人："mingzigequ"< ***@***.*** &gt;; 发件时间：2022/12/31 22:26 收件人："qxinGitHub/searchEngineJump"< ***@***.*** &gt;; 抄送人："CangWei"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;; 主题：Re: [qxinGitHub/searchEngineJump] 在网页的输入框和任意地方选中文字，顶部就会弹出，很遮挡视线，且没有关闭此功能的按钮 (Issue #126) 赞同 &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

怎么解决的呢。

**Comment by CangWeiohh** [comment]
> > 已经解决了 仓唯 _**@**_.*** 原始邮件 发件人："mingzigequ"< _**@**_.*** >; 发件时间：2022/12/31 22:26 收件人："qxinGitHub/searchEngineJump"< _**@**_.*** >; 抄送人："CangWei"< _**@**_.*** >;"Author"< _**@**_.*** >; 主题：Re: [qxinGitHub/searchEngineJump] 在网页的输入框和任意地方选中文字，顶部就会弹出，很遮挡视线，且没有关闭此功能的按钮 (Issue #126) 赞同 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 怎么解决的呢。

我忘了, 这个问题是什么表现来着? 截图看看

**Comment by CurssedCoffin** [comment]
这个我大概知道，油猴不知道，暴力猴点图标，可以看到这个插件的设置，去设置-更多设置-划词 那条关掉，保存就可以了

**Comment by JerryYang-30** [comment]
> > > 已经解决了 仓唯 _**@**_.*** 原始邮件 发件人："mingzigequ"< _**@**_.*** >; 发件时间：2022/12/31 22:26 收件人："qxinGitHub/searchEngineJump"< _**@**_.*** >; 抄送人："CangWei"< _**@**_.*** >;"Author"< _**@**_.*** >; 主题：Re: [qxinGitHub/searchEngineJump] 在网页的输入框和任意地方选中文字，顶部就会弹出，很遮挡视线，且没有关闭此功能的按钮 (Issue #126) 赞同 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> > 
> > 
> > 怎么解决的呢。
> 
> 我忘了, 这个问题是什么表现来着? 截图看看

![3wz3lqnq wcd](https://github.com/user-attachments/assets/2cfea0d9-3d66-4dd2-ba81-1e700f0f55f2)
就是这样，不过楼下的朋友好像已经给出解决方法了😂

**Comment by JerryYang-30** [comment]
> 这个我大概知道，油猴不知道，暴力猴点图标，可以看到这个插件的设置，去设置-更多设置-划词 那条关掉，保存就可以了

噢噢，想起来了，油猴是在搜索页面有设置，然后关掉划词搜索
