### ISSUE TITLE
 Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'

### ISSUE THREAD

**Issue by shifenhutu** [qxinGitHub/searchEngineJump#136]
你好，我是一个前端开发，在 127.0.0.1 和 localhost  上   会报错

![image](https://user-images.githubusercontent.com/104620424/224213545-ee749132-0f04-4474-a2e5-36fecdaedc33.png)

![image](https://user-images.githubusercontent.com/104620424/224213564-3775966a-f469-4114-92e7-692b1234b757.png)

**Comment by Drwna** [comment]
自己加点代码不就好了
![image](https://user-images.githubusercontent.com/58726441/232990169-ec0615ce-be7a-4fc9-9556-8b9d5efbbeae.png)

**Comment by shifenhutu** [comment]
谢谢你，雷锋 @Drwna
