### ISSUE TITLE
更新历史写错时间了。。

### ISSUE THREAD

**Issue by xspoco** [qxinGitHub/searchEngineJump#3]
> version 5.15.6       2017-03-08
> 
> 修复谷歌图书会被错误隐藏的问题感谢评论区 tensun tsai 反馈
> 百度学术界面无搜索框
> 此版本开始默认折叠当前搜索分类
> version 5.15.5       2017-03-05
> 
> 修改a站搜索连接，修复a站样式
> version 5.15.4       2017-02-15
> 
> 添加搜狗搜索
> version 5.15.3       2017-01-19
> 
> 谷歌搜索界面，，错误地隐藏了下载分类下的谷歌搜索 感谢评论区wsxy162 反馈
> version 5.15.2       2017-01-07
> 
> “打开方式”总会自动跳回“默认页面”而不是“新标签打开” 感谢评论区cll12反馈
> 
> 

现在已经2018年了。。

**Comment by qxinGitHub** [comment]
感谢反馈，一直用的复制粘贴，疏忽了
